# Generated by Django 3.0.1 on 2020-01-01 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20200101_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='owner',
        ),
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=models.FileField(help_text='eg:  file igaragaza raporo utanze', upload_to='reports'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.ForeignKey(help_text="eg: raporo y' imari ni igena migambi", on_delete=django.db.models.deletion.CASCADE, to='report.ReportType'),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='igihe_itangirwa',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Icyumweru'), (2, 'Ukwezi'), (3, 'Igihembwe'), (4, 'Amezi atandatu'), (5, 'Umwaka')], help_text='eg: Icyumweru, Ukwezi etc..'),
        ),
    ]
