# Generated by Django 3.0.1 on 2019-12-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20191228_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='date',
            new_name='submited_date',
        ),
    ]
