# Generated by Django 3.0.1 on 2020-01-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20200101_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='submited_date',
        ),
        migrations.AddField(
            model_name='report',
            name='submitted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
