# Generated by Django 3.0.1 on 2020-01-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20191222_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umuryango',
            name='icyiciro',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 3)], default=0),
        ),
    ]
