# Generated by Django 3.0.1 on 2020-01-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20200101_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umuryango',
            old_name='umudugudu',
            new_name='village',
        ),
        migrations.AlterField(
            model_name='umuryango',
            name='icyiciro',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
